spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: eletronicPoint
              uri: lb://EletronicPoint
              predicates:
                - Path=/eletronicPoint/**
              filters:
                - StripPrefix=1
                - AuthenticationFilter

            - id: authentication
              uri: lb://Authentication
              predicates:
                - Path=/auth/**
              filters:
                  - StripPrefix=1
server:
  port: 8282

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/